"""Add phone number to user

Revision ID: 031c2e6e976e
Revises: f90fcc1b8572
Create Date: 2026-08-03 11:59:26.375944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031c2e6e976e'
down_revision = 'f90fcc1b8572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.drop_column('leave_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_balance', sa.INTEGER(), nullable=False))
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
