"""Add profile and subscription fields to Organization

Revision ID: 3c4ec43ddd93
Revises: c919042cd97c
Create Date: 2026-08-13 14:55:06.707189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4ec43ddd93'
down_revision = 'c919042cd97c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('employee_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subscription_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('subscription_start_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('subscription_start_date')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('subscription_type')
        batch_op.drop_column('employee_count')
        batch_op.drop_column('website')
        batch_op.drop_column('address')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('industry')

    # ### end Alembic commands ###
