"""Add OrgRole and OrgPractice models

Revision ID: 43819dac438d
Revises: 6963a0caf0e8
Create Date: 2026-08-14 16:51:35.993088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43819dac438d'
down_revision = '6963a0caf0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_practice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_org_role_id', 'org_role', ['org_role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_org_role_id', type_='foreignkey')
        batch_op.drop_column('org_role_id')

    op.drop_table('org_role')
    op.drop_table('org_practice')
    # ### end Alembic commands ###
