"""Switch Invite and User to FK-based org_role and org_practice

Revision ID: 64d1cefa5ad0
Revises: 43819dac438d
Create Date: 2026-08-17 15:36:53.261645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d1cefa5ad0'
down_revision = '43819dac438d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_role_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('org_practice_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_invite_org_practice_id', 'org_practice', ['org_practice_id'], ['id'])
        batch_op.create_foreign_key('fk_invite_org_role_id', 'org_role', ['org_role_id'], ['id'])
        batch_op.drop_column('practice')
        batch_op.drop_column('role')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_practice_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_org_practice_id', 'org_practice', ['org_practice_id'], ['id'])
        batch_op.drop_column('practice')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('practice', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('fk_user_org_practice_id', type_='foreignkey')
        batch_op.drop_column('org_practice_id')

    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('practice', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('fk_invite_org_practice_id', type_='foreignkey')
        batch_op.drop_constraint('fk_invite_org_role_id', type_='foreignkey')
        batch_op.drop_column('org_practice_id')
        batch_op.drop_column('org_role_id')

    # ### end Alembic commands ###
