"""Add name, email, role, practice, manager to Invite

Revision ID: 6963a0caf0e8
Revises: ccda8660a1b3
Create Date: 2026-08-13 17:13:31.952933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6963a0caf0e8'
down_revision = 'ccda8660a1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('practice', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_invite_manager_id', 'user', ['manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invite_manager_id', type_='foreignkey')
        batch_op.drop_column('manager_id')
        batch_op.drop_column('practice')
        batch_op.drop_column('role')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
