"""Make Holiday.organization_id required

Revision ID: c919042cd97c
Revises: 43c64eca41fb
Create Date: 2026-08-06 15:12:19.914471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c919042cd97c'
down_revision = '43c64eca41fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holiday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_holiday_organization_id', 'organization', ['organization_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_organization_id', 'organization', ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_organization_id', type_='foreignkey')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('holiday', schema=None) as batch_op:
        batch_op.drop_constraint('fk_holiday_organization_id', type_='foreignkey')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
