"""Restore leave_balance, add phone number

Revision ID: fd00cd0ea2a7
Revises: 031c2e6e976e
Create Date: 2026-08-03 12:07:16.115998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd00cd0ea2a7'
down_revision = '031c2e6e976e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_balance', sa.Integer(), nullable=False, server_default='24'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('leave_balance')

    # ### end Alembic commands ###
